# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/xiaomi/toco-miuicamera/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/toco-miuicamera/common

PRODUCT_PACKAGES += \
    MiuiCamera \
    MiuiExtraPhoto
