# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/xiaomi/toco-miuicamera/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/toco-miuicamera/common

PRODUCT_COPY_FILES += \
    vendor/xiaomi/toco-miuicamera/common/proprietary/system/etc/public.libraries-xiaomi.txt:$(TARGET_COPY_OUT_SYSTEM)/etc/public.libraries-xiaomi.txt

PRODUCT_PACKAGES += \
    libarcsoft_single_chart_calibration \
    libcamera_algoup_jni.xiaomi \
    libcamera_mianode_jni.xiaomi \
    libdoc_photo \
    libdoc_photo_c++_shared \
    libSNPE \
    MiuiCamera \
    MiuiExtraPhoto
